### ISSUE TITLE
Beard disappears after equipping headgear [BUG]

### ISSUE THREAD

**Issue by Arodist** [Geborgen/nordic-souls#74] opened 2024-05-14 17:08 UTC
**Describe The Bug**
Beard disappears after equipping headgear.

**Expected Behavior**
Facial hair should remain visible after equipping helmet.

**Screenshots**
Note that when using showracemenu, the correct beard selection is still applied, but the actual beard is not visible. Moving the slider to either direction and then returning to the selection fixes it temporarily.
![image](https://github.com/Geborgen/nordic-souls/assets/98994676/f75a6186-f11a-4597-9248-0620294f9701)

**List Version**
v2.3.4.1

**Comment by Geborgen** [comment] 2024-05-26 20:11
Cannot reproduce.
- Is this any helmet or a certain helmet in particular?
- Does any other part of your character mess up, or just the beard?
On occasion, my face will break, and entering racemenu restores it. I've never been able to narrow this down so I wonder if this is a similar issue.

**Comment by Geborgen** [comment] 2024-06-06 20:25
Closing due to lack of information + cannot reproduce

**Closed by Geborgen** 2024-06-06 20:25 UTC
