### ISSUE TITLE
[BUG] Gourmet Buffs not applying

### ISSUE THREAD

**Issue by Roninburger** [Geborgen/nordic-souls#70] opened 2024-04-15 13:29 UTC
**Describe The Bug**
Gourmet Buffs are not working in spite of eating food that improves magicka/stamina/health regen together.

**Expected Behavior**
Gourmet buffs are supposed to apply.

**Send Your Crash Log**
No Crash Log

**Screenshots**

**List Version**
2.3.3.1

**Additional Context**
Attached Save File here
[Save304_43E410A1_0_5261766F6E61_Tamriel_010658_20220525162906_31_1.zip](https://github.com/Geborgen/nordic-souls/files/14979584/Save304_43E410A1_0_5261766F6E61_Tamriel_010658_20220525162906_31_1.zip)

**Comment by Geborgen** [comment] 2024-05-26 20:16
Cannot reproduce. Gourmet buffs apply correctly. Please provide more context, what isn't working?

**Comment by Geborgen** [comment] 2024-06-06 18:56
Closing due to lack of information.

**Closed by Geborgen** 2024-06-06 18:56 UTC
